apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: www
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`www.meyn.fr`)
    services:
    - name: www
      port: 80
  tls:
    certResolver: le
---
apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: default
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - image: docker.io/olopost/blog:0.3
          imagePullPolicy: Always
          name: blog
      imagePullSecrets:
        - name: regcred
